# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

resources:
- repo: self

variables:
  buildId: '$(Build.BuildId)'
  tag: 'dev'
  repository: 'vsite-web-fe'
  container: 'web_fe'

pool: Default

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build image
    steps:
    - task: CmdLine@2
      inputs:
        script: 'pwd && ls -a'
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: '$(repository)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
- stage: Deploy
  displayName: Deploy to nginx
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: CmdLine@2
      inputs:
        script: 'cd /home/ubuntu/deployments/ && docker-compose up -d --no-recreate $(container)'
