# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  buildId: '$(Build.BuildId)'
  tag: 'dev'
  repository: 'vsite-web-fe'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: CmdLine@2
      inputs:
        script: 'whoami && echo Write your commands here.'
        
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: '$(repository)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
- stage: Run
  displayName: Run image
  jobs:
  - job: Run
    displayName: Run
    pool: Default
    steps:
    - task: CmdLine@2
      inputs:
        script: 'docker stop web && docker run -it --rm -d -p 80:80 --name web $(repository):$(tag)'
